
version: "3"
services:
  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    restart: always
    volumes:
      - ./.data/db:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: hubspace
      POSTGRES_USER: hubspace
      POSTGRES_PASSWORD: hubspace
  backend:
    container_name: backend-node
    build: 
      context: backend/.
    restart: always
    environment:
      TZ: Asia/Bangkok
      db_host: postgresql
    ports:
      - 3000:3000
  frontend:
    container_name: frontend-node
    build: 
      context: frontend/.
    restart: always
    environment:
      TZ: Asia/Bangkok
      domain: backend
    environment:
      TZ: Asia/Bangkok
    ports:
      - 80:80